name: bubble_showcase_example
description: Demonstrates how to use the bubble_showcase plugin.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  bubble_showcase:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
  speech_bubble: ^0.0.7

flutter:
  uses-material-design: true
