name: bubble_showcase
description: BubbleShowcase is a small but powerful flutter package that allows you to highlight specific parts of your app to explain them to the user or to show your app new features.
version: 2.0.0
homepage: https://github.com/Skyost/BubbleShowcase

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=2.0.0 <3.0.0'

dev_dependencies: 
  flutter_lints: '>=3.0.1'
